
$define texture_path "textures/block.png"

t = texture_path

cube_m = "models/box.obj"
sphere_m = "models/sphere.obj"

planet {
    mesh(sphere_m, UNTEXTURED, [0, 0, 0], [0, 0, 0], [10, 10, 200])
    pos(3, 0, 0)
}

sphere {
    mesh(sphere_m, UNTEXTURED, [0, 0, 0], [0, 0, 0], [200, 10, 200])
    pos(3, 0, 0)
    add(planet)
}

cube {
    mesh(cube_m, TEXTURED, t, [0, 0, 0], [0, 0, 0], [10, 200, 120])
    pos(0, 0, 0)
    add(sphere)
}

place(cube)